# Generated by Django 6.0.6 on 2026-06-24 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(max_length=1000)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='posts/')),
                ('tipo', models.CharField(choices=[('immagine', 'Immagine'), ('video', 'Video')], default='immagine', max_length=10)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=2200)),
                ('data_creazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('archiviato', models.BooleanField(default=False)),
                ('eliminato_da_moderatore', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('spam', 'Spam'), ('odio', "Incitamento all'odio"), ('violenza', 'Contenuto violento'), ('altro', 'Altro')], max_length=20)),
                ('descrizione', models.TextField(blank=True, max_length=500)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('risolta', 'Risolta'), ('ignorata', 'Ignorata')], default='in_attesa', max_length=20)),
                ('creata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creata_il'],
            },
        ),
    ]