# Generated by Django 6.0.6 on 2026-06-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commento',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commento',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='commenti_con_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commento',
            name='risposta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='posts.commento'),
        ),
        migrations.AddField(
            model_name='post',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_con_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='salvati_da',
            field=models.ManyToManyField(blank=True, related_name='post_salvati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='posts.post'),
        ),
        migrations.AddField(
            model_name='commento',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='posts.post'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='commento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='posts.commento'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='gestita_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni_gestite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni', to='posts.post'),
        ),
        migrations.AddField(
            model_name='segnalazione',
            name='segnalato_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni_inviate', to=settings.AUTH_USER_MODEL),
        ),
    ]